[project]
name = "calculator"
version = "0.1.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.13"
namespace_packages = true
mypy_path = "src"

[tool.uv.sources]
calculator = { path = "." }
